the_techbox/urls.py
from django.contrib import admin
from django.urls import path, include,re_path  
from rest_framework.routers import DefaultRouter
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt import views as jwt_views
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

def trigger_error(request):
    division_by_zero = 1 / 0



urlpatterns = [
    path('i18n/',include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('sentry-debug/', trigger_error),
    path('', include('apps.authenticate.urls')),
    path('', include('apps.product.urls')),
    path('chat_boat/',include('apps.fb_chatboat.urls'))

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/product/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Employee(models.Model):
    DESIGNATION = (
          ("Team Lead", "Team Lead"),
          ("Sr. Developer", "Sr. Developer"),
          ("Jr. Developer", "Jr. Developer"),
    )
    name = models.CharField(max_length=100)
    designation = models.CharField(choices=DESIGNATION,max_length=100)
    email = models.EmailField()
    mobile = models.CharField(max_length=10)

    def __str__(self):
        return self.name
    


class Item(models.Model):
    name = models.CharField(max_length=100)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class ItemAssign(models.Model):
    assign_to = models.ForeignKey('Employee',on_delete=models.CASCADE)
    assign_item = models.ForeignKey('Item',on_delete= models.CASCADE)
    assign_date = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return self.assign_to.name

class SellItems(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()

    def __str__(self):
        return self.name

templates/dashboard/addemployee.html
{% extends "layouts/base.html" %}

{% load i18n %}

{% block title %} Add Employee {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">{% trans 'Register' %}</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">{% trans 'Authentication' %}</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">{% trans 'Register' %}</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                    <script>
                        {% if messages %}
                            {% for message in messages %}
                            
                                alert('{{ message }}');
                           
                            {% endfor %}

                        {% endif %}
                     </script>

                    </div>
                    <h2>{% trans 'Add Employee' %}</h2>
                </div>
                
                <form method="post" action="">

                    {% csrf_token %}

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="icon-user"></i>
                                            </span>
                                        </div>
                                        {{ emp.name }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fas fa-desktop"></i>
                                            </span>
                                        </div>
                                        {{ emp.designation }}
                                    </div>
                                </div>
                                

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fa fa-at"></i>
                                            </span>
                                        </div>
                                        {{ emp.email }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fa fa-id-card"></i>
                                            </span>
                                        </div>
                                        {{ emp.mobile }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-action">
                        <button type="submit" class="btn btn-primary">{% trans 'Add Employee' %}</button>
                        &nbsp; &nbsp;
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/dashboard/employedata.html
{% extends "layouts/base.html" %}

{% load i18n %}

{% block title %} Employee List {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
{% if request.user.is_authenticated %}
{% if messages %}
{% for message in messages %}

{{ message }}

{% endfor %}
{% endif %}
<div class="content">
	<div class="page-inner">
		<div class="page-header">
			<h4 class="page-title">{% trans 'Employee List' %}</h4>
			<ul class="breadcrumbs">
				<li class="nav-home">
					<a href="#">
						<i class="flaticon-home"></i>
					</a>
				</li>
				<li class="separator">
					<i class="flaticon-right-arrow"></i>
				</li>
			</ul>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title">{% trans "Employee's" %}</h4>
						<!-- Button trigger modal -->

					</div>
					<div class="card-body">
						<div class="table-responsive">
							<table id="mytable" class="table table-fluid">
								<thead>
									<tr class="text text-info">
										<th>{% trans 'Name' %}</th>
										<th>{% trans 'Designation' %}</th>
										<th>{% trans 'Email' %}</th>
										<th>{% trans 'Mobile' %}</th>
										<th class="text-center">{% trans 'Action' %}</th>
									</tr>
								</thead>
								<tbody>
									{% for emp in emp %}
									<tr>
										<td>{{emp.name}}</td>
										<td>{{emp.get_designation_display }}</td>
										<td>{{emp.email}}</td>
										<td>{{emp.mobile}}</td>
										<td>
											<div class="form-button-action">
												<a href="{%url 'update' emp.id %}"><button type="submit"
														data-toggle="tooltip" title=""
														class="btn btn-link btn-primary btn-lg"
														data-original-title="Edit">
														<i class="fa fa-edit">{% trans ' Update' %}</i>
													</button></a>
												<button type="button" data-toggle="modal" data-target="#exampleModal"
													class="btn btn-link btn-danger" data-original-title="Remove">
													<i class="fa fa-times">{% trans ' Remove' %}</i>
												</button>
												<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
													aria-labelledby="exampleModalLabel" aria-hidden="true">
													<div class="modal-dialog" role="document">
														<div class="modal-content">
															<div class="modal-header">
																<h5 class="modal-title" id="exampleModalLabel">{% trans 'Delete
																	Employee' %}
																</h5>
																<button type="button" class="close" data-dismiss="modal"
																	aria-label="Close">
																	<span aria-hidden="true">&times;</span>
																</button>
															</div>
															<div class="modal-body">
																<h2 class="text text-danger">{% trans 'Please Confirm To Delete' %}
																</h2>
															</div>
															<div class="modal-footer">
																<button type="button" class="btn btn-secondary"
																	data-dismiss="modal">{% trans 'Close' %}</button>
																<a href="{% url 'delete' emp.id %}"><button
																		type="button"
																		class="btn btn-danger">{% trans 'Delete' %}</button>
															</div>
														</div>
													</div>
												</div>

											</div>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
					<!-- Modal -->
				</div>
			</div>
		</div>
	</div>
</div>
{% endif %}

<!-- Button trigger modal -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
$(document).ready(function(){
	$('#mytable').DataTable();
});
</script>
{% endblock javascripts %}

templates/dashboard/empupdate.html
{% extends "layouts/base.html" %}

{% load i18n %}

{% block title %} Add Employee {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">{% trans 'Register' %}</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">{% trans 'Authentication' %}</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">{% trans 'Register' %}</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if messages %}
                            {% for message in messages %}
                            
                               {{ message }}
                           
                            {% endfor %}
                        {% endif %}
                
                    </div>
                </div>

                <form method="post" action="">

                    {% csrf_token %}

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="icon-user"></i>
                                            </span>
                                        </div>
                                        {{ form.name }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fas fa-desktop"></i>
                                            </span>
                                        </div>
                                        {{ form.designation }}
                                    </div>
                                </div>
                                

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fa fa-at"></i>
                                            </span>
                                        </div>
                                        {{ form.email }}
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fa fa-id-card"></i>
                                            </span>
                                        </div>
                                        {{ form.mobile }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-action">
                        <button type="submit" class="btn btn-primary">{% trans 'Update Employee' %}</button>
                        &nbsp; &nbsp;
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/dashboard/item.html
{% extends "layouts/base.html" %}

{% load i18n %}

{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


{% if request.user.is_authenticated %}
<div class="content">
	<div class="page-inner">
		<button class="btn btn-secondary btn-round float-right" data-target="#newempdata"
							data-toggle="modal">Add Items</button>
		<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">

  <thead>
    <tr>
      <th class="th-sm text-info">{% trans 'Name' %}

      </th>
      <th class="th-sm text-info">{% trans 'Avilability' %}
      </th>
      <th class="th-sm text-info">{% trans 'Assign'%}
      </th>

      <th class="th-sm text-info">{% trans 'Remove' %}

      </th>
    </tr>
  </thead>
  <tbody>
  	{% for item in items %}
    <tr>	
      <td>{{item.name}}</td>
      {% if item.status is True %}
        <td class="text-success">{% trans 'In Stock' %} </td>
      {% else %}
        <td class="text-danger">{% trans 'Out of Stock' %}</td>
      {% endif %}
    <td>
        <a href="{%url 'item-assign' %}"><button type="button"<i class="btn btn-sm fa fa-edit">{% trans 'Assign' %}</i></button></a>
    </td>

    <td>
        <div>
            <input class="btn btn-danger btn-sm" type="button"
            data-id="{{ item.id }}" id="tech-del-btn" value="Delete ">
        </div>
    </td>
    </tr>
    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <th class="th-lm">{% trans 'Name' %}

      </th>
      <th class="th-lm">{% trans 'Avilability' %}
      <th class="th-sm text-info">{% trans 'Assign' %}
      </th>
      </th>
      <th class="th-lm">{% trans 'Remove' %}
      </th>
    </tr>
  </tfoot>
</table>
	</div>
</div>
{% endif %}

<div class="modal fade" id="newempdata" tabindex="-1" role="dialog" aria-labelledby="newempdataTitle"
	aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header text-light">
				<h5 class="modal-title text text-info" id="newempdataTitle">{% trans 'Add Item' %}</h5>
				<button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form method='post' action="{% url 'itemlist' %}">
				{% csrf_token %}
				<div class="modal-body">
					<div id="tool-form">
						{{ item_add.as_p }}
						<br>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}
					</button>
					<button type="submit" class="btn btn-primary" id="emp-btn">{% trans 'Submit' %}</button></a>
				</div>
			</form>
		</div>
	</div>
</div>

<script>
	$(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
});
</script>
<script>
            $(document).ready(function () {
                $(document).on('click', '#tech-btn', function (e) {
                    e.preventDefault();
                    var tool_name = $('#tool-name').val();
                    var checked = $('#tool-status').is(':checked');
                    if (checked) {
                        var tool_status = "on"

                    }
                    var my_data = {
                        "name": tool_name,
                        "status": tool_status,
                        'csrfmiddlewaretoken': "{{ csrf_token }}",
                    }
                    $.ajax({
                        type: 'POST',
                        url: "{% url 'itemlist' %}",
                        data: my_data,
                        success: function (data) {
                            $('.new_tool').append(data);
                            $('#newtooldata').modal('hide');
                        },
                    });
                });

            });
        </script>

        <script>
            $(document).ready(function () {
                $(document).on('click', '#tech-update-btn', function (e) {
                    e.preventDefault();
                    var obj = $(this); // first store $(this) in obj
                    var id1 = $(this).data('id'); // get id of data using this

                    $(document).on('click', '#obj-update-btn', function (e) {
                        var id = id1
                        var name = $('#name').val()

                        var checked = $('#status').is(':checked');
                        if (checked) {
                            var tool_status = "on"
                        }
                        var my_data = {
                            'id': id,
                            "name": name,
                            "status": tool_status,
                            'csrfmiddlewaretoken': "{{ csrf_token }}",
                        }
                    });

                });
            });


        </script>

        <script>
            $(document).ready(function () {
                $(document).on('click', '#tech-del-btn', function (e) {
                    e.preventDefault();
                    var obj = $(this); // first store $(this) in obj
                    var id = $(this).data('id'); // get id of data using this


                    var my_data = {

                        "id": id,
                        'csrfmiddlewaretoken': "{{ csrf_token }}",
                    }
                    $.ajax({
                        type: 'POST',
                        url: "{% url 'itemdelete' %}",
                        data: my_data,
                        success: function (json) {
                            $(obj).closest("tr").remove();
                            alert("tool delete successfully ")
                        },
                    });
                });

            });
        </script>


{% endblock content %}

templates/dashboard/itemadd.html
{% extends "layouts/base.html" %}

{% load i18n %}

{% block title %} Add Item {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">{% trans 'Item Add' %}</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="#">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">{% trans 'Authentication' %}</a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="#">{% trans 'Register' %}</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                    <script>
                        {% if messages %}
                            {% for message in messages %}
                            
                                alert('{{ message }}');
                           
                            {% endfor %}

                        {% endif %}
                     </script>

                    </div>
                </div>

                <form method="post" action="">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">

                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                            {% trans 'Name' %}
                                            </span>
                                        </div>
                                        {{ item.name }}
                                    </div>
                                </div>
                                <div class="form-group float-left">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                            {% trans 'Status' %}
                                            </span>
                                        </div>
                                        {{ item.status }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-action">
                        <button type="submit" class="btn btn-primary">{% trans 'Add Item' %}</button>
                        &nbsp; &nbsp;
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/dashboard/success.html
{% load i18n %}

<html>
<head>
  <title>{% trans 'Thanks for your order!' %}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>
      {% trans 'We appreciate your business! If you have any questions, please email' %}
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>
    <a href={% url 'home' %} class="btn btn-sm btn-primary">{% trans 'Back To Home' %}</a>
  </section>
</body>
</html>